INSERT INTO BOOKMANAGER.BOOKS (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRICE) VALUES ('1', 'First Book', 'First Author', '30000');
INSERT INTO BOOKMANAGER.BOOKS (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRICE) VALUES ('2', 'Second Book', 'Second Author', '20000');
INSERT INTO BOOKMANAGER.BOOKS (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRICE) VALUES ('3', 'Third Book', 'Third Author', '15000');
INSERT INTO BOOKMANAGER.BOOKS (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRICE) VALUES ('4', 'Fourth Book', 'Fourth Author', '25000');
INSERT INTO BOOKMANAGER.BOOKS (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRICE) VALUES ('5', 'Fifth Book', 'Fifth Author', '80000');
INSERT INTO BOOKMANAGER.BOOKS (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRICE) VALUES ('6', 'Sixth Book', 'Sixth Author', '50000');
